# fixpoint_kadaiQ3sEwFL7
fixpoint採用試験の課題提出です。

プログラムは、各課題それぞれ以下のように実行できます。
 - 設問1
log4.txtにより実行する場合: 
```
python pro1.py log4.txt
```
実行結果は以下のとおりです。
```
# 故障状態
ipaddress: 192.168.1.1/24, failure period: 0 days 00:00:08 (2020-10-19 13:31:40 ~ 2020-10-19 13:31:48)
ipaddress: 192.168.1.1/24, failure period: 0 days 00:00:09 (2020-10-19 13:32:05 ~ 2020-10-19 13:32:14)
(省略)
ipaddress: 192.168.1.2/24, failure period: 0 days 00:00:10 (2020-10-19 14:18:27 ~ 2020-10-19 14:18:37)
ipaddress: 192.168.1.2/24, failure period: 0 days 00:00:36 (2020-10-19 14:19:03 ~ 2020-10-19 14:19:39)
総数:  207
```

 - 設問2
log4.txtにより実行する場合: 
```
python log4.txt 5
```
実行結果は以下のとおりです。
```
thon pro2.py log4.txt 5
ipaddress: 192.168.1.1/24, failure period: 0 days 00:00:55 (2020-10-19 13:50:15 ~ 2020-10-19 13:51:10)
ipaddress: 192.168.1.1/24, failure period: 0 days 00:01:04 (2020-10-19 14:09:54 ~ 2020-10-19 14:10:58)
(省略)
ipaddress: 192.168.1.2/24, failure period: 0 days 00:01:05 (2020-10-19 14:07:57 ~ 2020-10-19 14:09:02)
ipaddress: 192.168.1.2/24, failure period: 0 days 00:00:58 (2020-10-19 14:11:52 ~ 2020-10-19 14:12:50)
総数: 8
```

 - 設問3
 
 
 - 設問4
提出に間に合わせることができませんでした。
作成途中のものをアップロードしています(正常動作しません)


 - 他
使用したlog4.txtは、gen_logsample.pyにより乱数で生成されたものです。
